function(genproc)
    list(LENGTH LibFiles liblength)
    list(FIND LibFiles ${MainFile} LibContainsMain)

    if(liblength GREATER 1)

        list(REMOVE_ITEM LibFiles ${MainFile})

        if(${LibContainsMain} GREATER -1)
            message(STATUS "-------------------------------")
            message(STATUS "[x] ${PROJECT_TEST}")
            message(STATUS "[x] ${PROJECT_LIB}")
            message(STATUS "-------------------------------")
            genexe()
            genlib()
        else()
            message(STATUS "-------------------------------")
            message(STATUS "[ ] ${PROJECT_TEST}")
            message(STATUS "[x] ${PROJECT_LIB}")
            message(STATUS "-------------------------------")
            genlib()
        endif()

    else()
        if(liblength EQUAL 1 AND ${LibContainsMain} GREATER -1) # AND LibContainsMain
            message(STATUS "-------------------------------")
            message(STATUS "[x] ${PROJECT_TEST}")
            message(STATUS "[ ] ${PROJECT_LIB}")
            message(STATUS "-------------------------------")
            genexe()
        endif()
    endif()

    if(MADE_BUILD)
        message(STATUS "${PROJECT_NAME}: Build made")
    else()
        message(STATUS "${PROJECT_NAME}: Build skipped")
    endif()
endfunction()